### ISSUE TITLE
Problema installazione rmap

### ISSUE THREAD

**Issue by gianpieropa** [ARPA-SIMC/cosudo#90]
Stavo ricreando l'ambiente di sviluppo (a causa di un cambio di pc), ho installato tutti i pacchetti come da guida ma riscontro il seguente errore con dballe. La versione installata di dballe è la 8.15. Ho provato avviando rmap sia con la versione su copr, che con la versione su git. Ho provato anche ricreando il container di docker, ma nulla. Avete idee?
````
[root@7d8fb352ab93 python]# rmapweb
Rmapweb version 11.0
Daemon started with pid 160
Daemon stdout output
Daemon stderr output
import error:  dynamic
disable     :  ('dynamic', 'rest_framework')
dballe utilities disabled
Performing system checks...

Traceback (most recent call last):
  File "/usr/bin/rmapweb", line 189, in <module>
    sys.exit(main())  # (this code was run as script)
  File "/usr/bin/rmapweb", line 159, in main
    management.call_command("runserver",rmap.settings.port,use_reloader=False)
  File "/usr/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 95, in handle
    self.run(**options)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 104, in run
    self.inner_run(None, **options)
  File "/usr/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 390, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/lib/python3.6/site-packages/django/core/management/base.py", line 377, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/usr/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 399, in check
    for pattern in self.url_patterns:
  File "/usr/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 584, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/lib/python3.6/site-packages/django/utils/functional.py", line 80, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/lib/python3.6/site-packages/django/urls/resolvers.py", line 577, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.6/site-packages/rmap/urls.py", line 6, in <module>
    from .views import home,wizard,wizard2,wizard_done,wizard_error
  File "/usr/lib/python3.6/site-packages/rmap/views.py", line 16, in <module>
    import rmap.rmap_core
  File "/usr/lib/python3.6/site-packages/rmap/rmap_core.py", line 43, in <module>
    import dballe,io
  File "/usr/lib/python3.6/site-packages/dballe/__init__.py", line 3, in <module>
    import _dballe
ImportError: /lib64/libdballe.so.8: undefined symbol: _ZN7wreport7options23var_clamp_domain_errorsE


````

**Comment by gianpieropa** [comment]
Questi sono i comandi che ho utilizzato per l'installazione dei vari pacchetti. 
````
dnf -y install epel-release
dnf install yum-plugin-copr
dnf copr enable simc/stable
dnf copr enable pat1/rmap
dnf config-manager --set-enabled PowerTool
dnf install python3-rmap python3-django-cors-headers python3-
pyparsing python3-django-classy-tags arkimet dballe provami dballe-
web python3-netcdf4 netcdf-fortran netcdf-fortran-devel
````

**Comment by gianpieropa** [comment]
Risolto

**Comment by pat1** [comment]
credo dipenda da un aggiornamento del pacchetto wreport

**Comment by gianpieropa** [comment]
Sisi risolto. Un'altra domanda, ho importato dei dati da test.rmap.cc utilizzando il comando dadb import. I dati vengono correttamente visualizzati in showdata, ma le summary non prendono in considerazione quei dati. Devo configurare qualcosa?
![Schermata del 2021-01-25 11-37-27](https://user-images.githubusercontent.com/68102511/105695005-d8182880-5f01-11eb-9164-31df77056598.png)
![Schermata del 2021-01-25 11-36-40](https://user-images.githubusercontent.com/68102511/105695018-da7a8280-5f01-11eb-946c-baabb5c10313.png)

**Comment by pat1** [comment]
I summaries sono stati ottimizzati con cache specializzate quindi:
le sorgenti dei dati vengono configurate tramite la variabile BORINUD
dentro BORINUD c'è SOURCES
che a sua volta contiene ad esempio
 "class": "borinud.utils.source.DballeDB",
 "url": dsnreport_fixed,
 "explorer": "/rmap/dballe/report_fixed.json"

explorer è la cache specializzata per i summaries

una possibilità è impostare "explorer": None e l'esplorer verrà ricreato ogni query 
l'altra è generarlo periodicamente tramite il comando:
```
rmap-explorer --help
usage: rmap-explorer [-h] [--version] [--writeexplorer] [--alltype] [--nodballe] [--arkimet]
                     [--type {report,report_fixed,report_mobile,sample,sample_fixed,sample_mobile}]

Create explorer fron dballe DSN (default) or arkimet; explorer are used by BORINUD to cache summaries. Call this periodically from crontab or whe DB is updated

optional arguments:
  -h, --help            show this help message and exit
  --version             show program's version number and exit
  --writeexplorer       write explorer on permanent store
  --alltype             select ALL data level and type of data to elaborate
  --nodballe            disable build explorer for DBall.e
  --arkimet             build explorer for arkimet
  --type {report,report_fixed,report_mobile,sample,sample_fixed,sample_mobile}
                        select data level and type of data to elaborate
```
nel tuo caso penso possa funzionare:
```
rmap-explorer --alltype --writeexplorer
```

**Comment by gianpieropa** [comment]
Perfetto ha funzionato, grazie mille
